/*
 * generated by Xtext
 */
package nl.tue.ele.es.sdf3.editor.ui.contentassist

import nl.tue.ele.es.sdf3.editor.ui.contentassist.AbstractSDF3ProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SDF3ProposalProvider extends AbstractSDF3ProposalProvider {
}
