/*
 * generated by Xtext
 */
package nl.tue.ele.es.sdf3.editor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SDF3RuntimeModule extends nl.tue.ele.es.sdf3.editor.AbstractSDF3RuntimeModule {

}
