/*
 * generated by Xtext
 */
package nl.tue.ele.es.sdf3.editor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SDF3UiModule extends nl.tue.ele.es.sdf3.editor.ui.AbstractSDF3UiModule {
	public SDF3UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
